export type EmojiObject = {
  name: string;
  emoji: string;
};

export const emojis = [
  { name: 'grinningFace', emoji: '😀' },
  { name: 'grinningFaceWithBigEyes', emoji: '😃' },
  { name: 'grinningFaceWithSmilingEyes', emoji: '😄' },
  { name: 'beamingFaceWithSmilingEyes', emoji: '😁' },
  { name: 'grinningSquintingFace', emoji: '😆' },
  { name: 'grinningFaceWithSweat', emoji: '😅' },
  { name: 'faceWithTearsOfJoy', emoji: '😂' },
  { name: 'rollingOnTheFloorLaughing', emoji: '🤣' },
  { name: 'smilingFaceWithSmilingEyes', emoji: '😊' },
  { name: 'smilingFaceWithHalo', emoji: '😇' },
  { name: 'slightlySmilingFace', emoji: '🙂' },
  { name: 'upsideDownFace', emoji: '🙃' },
  { name: 'winkingFace', emoji: '😉' },
  { name: 'relievedFace', emoji: '😌' },
  { name: 'heartEyes', emoji: '😍' },
  { name: 'smilingFaceWithHearts', emoji: '🥰' },
  { name: 'starStruck', emoji: '🤩' },
  { name: 'faceBlowingAKiss', emoji: '😘' },
  { name: 'kissingFace', emoji: '😗' },
  { name: 'kissingFaceWithSmilingEyes', emoji: '😙' },
  { name: 'kissingFaceWithClosedEyes', emoji: '😚' },
  { name: 'faceSavouringFood', emoji: '😋' },
  { name: 'faceWithTongue', emoji: '😛' },
  { name: 'winkingFaceWithTongue', emoji: '😜' },
  { name: 'zanyFace', emoji: '🤪' },
  { name: 'squintingFaceWithTongue', emoji: '😝' },
  { name: 'moneyMouthFace', emoji: '🤑' },
  { name: 'huggingFace', emoji: '🤗' },
  { name: 'faceWithHandOverMouth', emoji: '🤭' },
  { name: 'shushingFace', emoji: '🤫' },
  { name: 'thinkingFace', emoji: '🤔' },
  { name: 'zipperMouthFace', emoji: '🤐' },
  { name: 'faceWithRaisedEyebrow', emoji: '🤨' },
  { name: 'neutralFace', emoji: '😐' },
  { name: 'expressionlessFace', emoji: '😑' },
  { name: 'faceWithoutMouth', emoji: '😶' },
  { name: 'smirkingFace', emoji: '😏' },
  { name: 'unamusedFace', emoji: '😒' },
  { name: 'faceWithRollingEyes', emoji: '🙄' },
  { name: 'grimacingFace', emoji: '😬' },
  { name: 'lyingFace', emoji: '🤥' },
  { name: 'pensiveFace', emoji: '😔' },
  { name: 'sleepyFace', emoji: '😪' },
  { name: 'droolingFace', emoji: '🤤' },
  { name: 'sleepingFace', emoji: '😴' },
  { name: 'faceWithMedicalMask', emoji: '😷' },
  { name: 'faceWithThermometer', emoji: '🤒' },
  { name: 'faceWithHeadBandage', emoji: '🤕' },
  { name: 'nauseatedFace', emoji: '🤢' },
  { name: 'faceVomiting', emoji: '🤮' },
  { name: 'sneezingFace', emoji: '🤧' },
  { name: 'hotFace', emoji: '🥵' },
  { name: 'coldFace', emoji: '🥶' },
  { name: 'woozyFace', emoji: '🥴' },
  { name: 'dizzyFace', emoji: '😵' },
  { name: 'explodingHead', emoji: '🤯' },
  { name: 'cowboyHatFace', emoji: '🤠' },
  { name: 'partyingFace', emoji: '🥳' },
  { name: 'smilingFaceWithSunglasses', emoji: '😎' },
  { name: 'nerdFace', emoji: '🤓' },
  { name: 'faceWithMonocle', emoji: '🧐' },
  { name: 'confusedFace', emoji: '😕' },
  { name: 'worriedFace', emoji: '😟' },
  { name: 'slightlyFrowningFace', emoji: '🙁' },
  { name: 'frowningFace', emoji: '☹' },
  { name: 'faceWithOpenMouth', emoji: '😮' },
  { name: 'hushedFace', emoji: '😯' },
  { name: 'astonishedFace', emoji: '😲' },
  { name: 'flushedFace', emoji: '😳' },
  { name: 'pleadingFace', emoji: '🥺' },
  { name: 'frowningFaceWithOpenMouth', emoji: '😦' },
  { name: 'anguishedFace', emoji: '😧' },
  { name: 'fearfulFace', emoji: '😨' },
  { name: 'anxiousFaceWithSweat', emoji: '😰' },
  { name: 'sadButRelievedFace', emoji: '😥' },
  { name: 'cryingFace', emoji: '😢' },
  { name: 'loudlyCryingFace', emoji: '😭' },
  { name: 'faceScreamingInFear', emoji: '😱' },
  { name: 'confoundedFace', emoji: '😖' },
  { name: 'perseveringFace', emoji: '😣' },
  { name: 'disappointedFace', emoji: '😞' },
  { name: 'downcastFaceWithSweat', emoji: '😓' },
  { name: 'wearyFace', emoji: '😩' },
  { name: 'tiredFace', emoji: '😫' },
  { name: 'faceWithSteamFromNose', emoji: '😤' },
  { name: 'poutingFace', emoji: '😡' },
  { name: 'angryFace', emoji: '😠' },
  { name: 'faceWithSymbolsOnMouth', emoji: '🤬' },
  { name: 'smilingFaceWithHorns', emoji: '😈' },
  { name: 'angryFaceWithHorns', emoji: '👿' },
  { name: 'skull', emoji: '💀' },
  { name: 'skullAndCrossbones', emoji: '☠' },
  { name: 'pileOfPoo', emoji: '💩' },
  { name: 'clownFace', emoji: '🤡' },
  { name: 'ogre', emoji: '👹' },
  { name: 'goblin', emoji: '👺' },
  { name: 'ghost', emoji: '👻' },
  { name: 'alien', emoji: '👽' },
  { name: 'alienMonster', emoji: '👾' },
  { name: 'robot', emoji: '🤖' },
  { name: 'grinningCat', emoji: '😺' },
  { name: 'grinningCatWithSmilingEyes', emoji: '😸' },
  { name: 'catWithTearsOfJoy', emoji: '😹' },
  { name: 'smilingCatWithHeartEyes', emoji: '😻' },
  { name: 'catWithWrySmile', emoji: '😼' },
  { name: 'kissingCat', emoji: '😽' },
  { name: 'wearyCat', emoji: '🙀' },
  { name: 'cryingCat', emoji: '😿' },
  { name: 'poutingCat', emoji: '😾' },
];

export const findEmojiByName = (name: string) => {
  const emojiObj = emojis.find((emoji) => emoji.name === name);
  return emojiObj ? emojiObj.emoji : null;
};
