name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn workspaces foreach --all --parallel install --immutable
      - run: npx nx affected -t lint
      - run: npx nx affected -t test --configuration=ci
      - run: npx nx affected -t build
      - run: npx nx affected -t release:package --parallel=1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}