name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies with Frozen Lockfile
        run: |
          yarn install --frozen-lockfile

      - name: Reinstall Dependencies for Specific Projects
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: |
          npx nx run-many --target=reinstall --projects=justaname-express,justaname-next-app,justaname-next-pages,justaname-fastify,justaname-nestjs,justaname-expo-full,justaname-react,justaname-hapi,justaname-koa,justaname-expo-frontend --parallel

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Check for Updated yarn.lock Files
        run: |
          git add examples/*/yarn.lock
          git diff --cached --exit-code || (git commit -m "CI: Update yarn.lock files" && git push origin main)

      - name: Build and Test
        run: |
          npx nx affected -t lint
          npx nx affected -t test --configuration=ci --passWithNoTests --exclude=justaname-mono-sdk
          npx nx affected -t build

      - name: Pull latest changes from main
        run: git pull origin main

      - name: Release
        run: npx nx release --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
